# arguments for dataset
dataset: cityscapes
nclass: 19
crop_size: 801
data_root: /nfs/bigtensor.cs.stonybrook.edu/add_disk0/ironman/data/cityscapes
#bbox_path: /nfs/bigtensor.cs.stonybrook.edu/add_disk1/ironman/fastrcnn/pascal_coco/results_bestmodel3971/train_split_92_images_bounding_box_95
#bbox_lbl_path: /nfs/bigtensor.cs.stonybrook.edu/add_disk1/ironman/fastrcnn/pascal_coco/results_bestmodel3971/train_split_92_new_result_images_labels_95
#bbox_score_path: /nfs/bigtensor.cs.stonybrook.edu/add_disk1/ironman/fastrcnn/pascal_coco/results_bestmodel3971/train_split_92_new_result_images_scores_95
bbox_path: /nfs/bigtensor.cs.stonybrook.edu/add_disk1/ironman/fastrcnn/nopretrained_tlight_poles_sign_wall_fence_terrain_results/train_split0_183_new_result_images_bounding_box_90
bbox_lbl_path: /nfs/bigtensor.cs.stonybrook.edu/add_disk1/ironman/fastrcnn/nopretrained_tlight_poles_sign_wall_fence_terrain_results/train_split0_183_new_result_images_labels_90
bbox_score_path: /nfs/bigtensor.cs.stonybrook.edu/add_disk1/ironman/fastrcnn/nopretrained_tlight_poles_sign_wall_fence_terrain_results/train_split0_183_new_result_images_scores_90
K: 5
# arguments for training
epochs: 240
batch_size: 1 # per GPU x 4 GPUs
lr: 0.005
lr_multi: 1.0
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 200000
conf_thresh: 0

# arguments for model
backbone: resnet101
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
